#!/bin/bash
# vim: set ft=sh

gosub list \
  -a github.com/concourse/fly \
  -a github.com/docurated/atc/cmd/... \
  -a github.com/concourse/blackbox/cmd/... \
  -a github.com/concourse/baggageclaim/cmd/... \
  -a github.com/concourse/tsa/cmd/... \
  -t github.com/concourse/testflight/... \
  -t github.com/docurated/atc/... \
  -t github.com/concourse/tsa/... \
  -t github.com/concourse/blackbox/integration/... \
  -t github.com/concourse/baggageclaim/integration/... \
  -a github.com/vito/gosub \
  -a github.com/jteeuwen/go-bindata/go-bindata
